### ISSUE TITLE
0.0.0-alpha1 roadmap

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#1]
The first step of working towards revolve2 `1.0.0` is creating a simple evolutionary loop using CI's modular robots. This the goal of release `0.0.0-alpha1`. This issue provides a list of requirements for this release.

See branch [0.0.0-alpha1](https://github.com/ci-group/revolve2/tree/0.0.0-alpha1).

- [x] Isaac Gym simulation environment. #6 
- [x] Modular robot framework that can be used to create robots for the simulation environment. #7 
- [x] An optimization framework for evolutionary processes. #8 
- [x] A database system to store results and provide recovery in case of failure. #9 #28
- [x] Successfully run a basic experiment. Do analysis together with a researcher. Create and resolve issues accordingly.
- [x] Analysis tools. #21
- [x] Simulation log #22
- [x] Robot size querying #31

**Comment by surgura** [comment]
#13
